# ---------------------------------------------------------------------------
# The measurement tables. Each replaced a hand-written list somewhere in the
# package that turned out to be wrong (a runtime list with a dead name,
# noise preferences no measurement supported, a scale question nobody had
# asked), so each is generated by data-raw/measure_engines.R and rebuilt by
# data-raw/build_measured_data.R. Numbers are for this package's defaults
# at the release, on one Linux x86-64 machine (AMD EPYC), and the
# registry's measured columns (cpt_methods()) and cpt_recommend() read them.
# ---------------------------------------------------------------------------

#' Engine runtimes by series length
#'
#' One timed \code{cpt_detect()} call per engine and length, each in its own
#' R process running an installed (byte-compiled) build, after a warm-up
#' call, so the time is the fit and not loading or compiling anything, with
#' a time cap of 120 seconds (300 at a million). A length is attempted only
#' when the previous one finished in under ten seconds.
#' One run per cell: this answers "will it finish?", and is not a basis for
#' claiming one engine is faster than another by a given factor.
#'
#' @format A tibble with one row per engine and length attempted:
#' \describe{
#'   \item{method}{the method, as \code{cpt_detect()} takes it.}
#'   \item{n}{the series length: 1,000, 10,000, 100,000 or 1,000,000, with
#'     four mean changes of two noise standard deviations (three coordinates
#'     for the multivariate engines).}
#'   \item{seconds}{elapsed time of the fit.}
#'   \item{k}{changepoints reported (four are real; a single-change method
#'     reports one).}
#'   \item{status}{\code{"ok"}, \code{"timeout"} or \code{"error"}.}
#' }
#' @source \code{data-raw/measure_engines.R} (part \code{runtime}).
#' @seealso \code{\link{cpt_methods}()}'s \code{cost} and \code{max_n}
#'   columns, \code{\link{cpt_recommend}()}.
#' @family measurement tables
#' @examples
#' subset(cpt_runtimes, n == 1e5 & status == "ok")
"cpt_runtimes"

#' Invariances of every engine's answer
#'
#' Five replicates of a 200-point series with changes at 70 and 140 (a
#' 3-coordinate version for the multivariate engines), detected as given and
#' transformed. A correct mean-change detector returns the same
#' changepoints on \code{10 * x}, \code{0.1 * x} and \code{x + 100}, and
#' \code{n - cp} on the reversed series.
#'
#' @format A tibble with one row per engine:
#' \describe{
#'   \item{method}{the method.}
#'   \item{reps}{replicates that ran.}
#'   \item{k}{median changepoints on the series as given.}
#'   \item{scale_invariant}{the same answer at \code{x}, \code{10 * x} and
#'     \code{0.1 * x} in at least four of five replicates. \code{FALSE} for
#'     the Gaussian-cost engines that assume unit noise, which is why
#'     \code{cpt_detect()} warns when one is handed noise far from unit
#'     scale.}
#'   \item{shift_invariant}{the same answer on \code{x + 100}.}
#'   \item{reversal_rate}{share of replicates whose reversed series gives
#'     the mirrored answer.}
#'   \item{sequential}{the reversal test fails in most replicates: the
#'     answer depends on the direction of time.}
#'   \item{concat_k}{median changepoints on \code{c(x, x)} (four expected,
#'     one for a single-change design).}
#'   \item{dup_k}{median changepoints when every observation is repeated
#'     twice, which makes the noise strongly autocorrelated: a measure of how
#'     badly the engine fails when its independence assumption does.}
#' }
#' @source \code{data-raw/measure_engines.R} (part \code{invariance}).
#' @family measurement tables
#' @examples
#' subset(cpt_invariances, !scale_invariant)$method
"cpt_invariances"

#' False positives and power under four noise regimes
#'
#' Ten replicates of a 300-point series with mean changes of two marginal
#' standard deviations at 100 and 200, under independent Gaussian noise,
#' heavy-tailed noise (\eqn{t_3}, scaled to unit variance), AR(1) noise with
#' \eqn{\rho = 0.7} and heteroscedastic noise (standard deviations 0.5, 1
#' and 2.5 by segment), for every univariate engine at its default and at
#' each setting of its noise-model argument. A recommendation is a call,
#' not a name: \code{smuce} and \code{smuce} with \code{family = "hsmuce"}
#' are different detectors.
#'
#' @format A tibble with one row per engine, setting and regime:
#' \describe{
#'   \item{method, setting}{the engine and the argument setting
#'     (\code{"default"} or the argument as written).}
#'   \item{call}{the \code{cpt_detect()} call the row measures.}
#'   \item{regime}{\code{"iid"}, \code{"heavy"}, \code{"ar1"} or
#'     \code{"hetero"}.}
#'   \item{reps}{replicates that ran.}
#'   \item{hits}{mean number of the two real changes found within ten
#'     positions.}
#'   \item{fp}{mean number of reported changepoints more than ten positions
#'     from either.}
#' }
#' @source \code{data-raw/measure_engines.R} (part \code{noise}).
#' @family measurement tables
#' @examples
#' ar <- subset(cpt_noise_benchmark, regime == "ar1")
#' ar[order(ar$fp), c("call", "hits", "fp")]
"cpt_noise_benchmark"

#' False positives and power by data type
#'
#' Ten replicates of a 400-point series with one change at 200, at
#' comparable effect sizes across four data types: Gaussian (a shift of 1.4
#' standard deviations), Bernoulli (probability 0.15 to 0.75), Poisson (rate
#' 2 to 10) and a proportion (binomial of 20, 0.25 to 0.6). Each engine is
#' at its default, as a user who does not set \code{family} gets it.
#'
#' @format A tibble with one row per engine and data type:
#' \describe{
#'   \item{method}{the engine.}
#'   \item{data_type}{\code{"gaussian"}, \code{"bernoulli"},
#'     \code{"poisson"} or \code{"proportion"}.}
#'   \item{reps}{replicates that ran.}
#'   \item{hit_rate}{share of replicates finding the change within 20
#'     positions.}
#'   \item{fp}{mean number of other reported changepoints.}
#' }
#' @source \code{data-raw/measure_engines.R} (part \code{datatype}).
#' @family measurement tables
#' @examples
#' b <- subset(cpt_data_types, data_type == "bernoulli")
#' b[order(-b$fp), ][1:5, ]
"cpt_data_types"

#' False alarms on pure noise at scale
#'
#' Independent Gaussian noise with no changepoint anywhere, at 1,000 (50
#' replicates), 10,000 (10) and 100,000 (6) observations, for the engines
#' the runtime table shows finishing that length quickly. Every changepoint
#' reported is a false alarm.
#'
#' @format A tibble with one row per engine and length:
#' \describe{
#'   \item{method}{the engine.}
#'   \item{n}{the series length.}
#'   \item{reps}{replicates that ran.}
#'   \item{size}{share of replicates reporting at least one changepoint.}
#'   \item{mean_fp}{mean number of changepoints reported.}
#' }
#' @source \code{data-raw/measure_engines.R} (part \code{null}).
#' @family measurement tables
#' @examples
#' subset(cpt_null_sizes, n == max(n))
"cpt_null_sizes"

#' What the package promises, against what it delivers
#'
#' The calibration suite: every guarantee the documentation states that a
#' simulation can check, with the realised value and its Monte Carlo
#' standard error. Location intervals are scored for coverage (conditional
#' on a changepoint landing within 20 positions of the truth), tests for
#' their size at 5\% on data with no change, and monitors for their
#' in-control run length. The row for \code{cpt_test()} at a location the
#' data chose is there to show what \code{selection_adjusted = FALSE}
#' means: its nominal 5\% is not what it delivers.
#'
#' @format A tibble with one row per guarantee and setting:
#' \describe{
#'   \item{guarantee}{what is promised, and by which function.}
#'   \item{call}{the call that was measured.}
#'   \item{setting}{the data and the options it was measured on.}
#'   \item{kind}{\code{"coverage"}, \code{"size"} or \code{"run_length"}.}
#'   \item{nominal}{the promised value: a confidence level, a test's level
#'     or an average run length (for the e-detector, a lower bound).}
#'   \item{realised}{the measured value.}
#'   \item{mcse}{its Monte Carlo standard error.}
#'   \item{reps}{replicates that counted (for coverage, those that detected
#'     the change).}
#' }
#' @source \code{data-raw/calibration.R}.
#' @seealso The calibration article on the package website,
#'   \url{https://pursuitofdatascience.github.io/ggchangepoint/articles/calibration.html}.
#' @family measurement tables
#' @examples
#' cpt_calibration[, c("call", "nominal", "realised", "mcse")]
"cpt_calibration"
